_format_version: "3.0"
_transform: true

services:
  - name: auth-service
    url: http://192.168.29.238:3001
    routes:
      - name: auth-route
        paths:
          - /auth
        strip_path: true
        methods: [GET, POST, PUT, DELETE]
    plugins:
      - name: cors
        config:
          origins: ["*"]
          methods: [GET, POST, PUT, DELETE, OPTIONS]
          headers: [Accept, Authorization, Content-Type]
          exposed_headers: [X-Auth-Token]
          credentials: true
          max_age: 3600

      - name: rate-limiting
        config:
          minute: 10
          hour: 1000
          policy: local
          redis:
            host: redis
            port: 6379
            timeout: 2000
            database: 0

  - name: user-service
    url: http://192.168.29.238:3002
    routes:
      - name: user-route
        paths:
          - /users
        strip_path: false
        methods: [GET, POST, PUT, DELETE]
    plugins:
      - name: jwt
        config:
          secret_is_base64: false
          key_claim_name: iss
          claims_to_verify: [exp]

      - name: rate-limiting
        config:
          minute: 50
          hour: 500
          policy: redis
          redis:
            host: redis
            port: 6379

      - name: request-transformer
        config:
          add:
            headers:
              - X-Service-Name:user-service

  - name: notification-service
    url: http://192.168.29.238:3003
    routes:
      - name: notification-route
        paths:
          - /notifications
        strip_path: false
        methods: [GET, POST, PUT, DELETE]
    plugins:
      - name: jwt
        config:
          secret_is_base64: false
          key_claim_name: iss
          claims_to_verify: [exp]

      - name: cors
        config:
          origins: ["*"]
          methods: [GET, POST, PUT, DELETE, OPTIONS]
          headers: [Accept, Authorization, Content-Type]
          exposed_headers: [X-Notification-Id]
          credentials: true
          max_age: 3600

      - name: rate-limiting
        config:
          minute: 80
          hour: 800
          policy: redis
          redis:
            host: redis
            port: 6379

      - name: request-transformer
        config:
          add:
            headers:
              - X-Service-Name:notification-service
